# Solicitação Dimap 1

#### **Solicitado por**: Bruno Carano

Será que você consegue me ajudar gerando mais 4 colunas adicionais nesse mesmo shape?

Seriam elas:

1 - CODLSQ (campo tipo texto; 6 caracteres) = junção de código do logradouro + dígito do código do logradouro + setor + quadra  ... todos da tabela dado avaliativo

2 - tp_uso_imovel : código de uso da tabela dado avaliativo

3 - tp_padrao_construcao : código de padrão construtivo da tabela dado avaliativo

4 - tp_zonauso: nesse colocar o código do tipo de zona de uso que predomina no lote, baseado no seu estudo do zoneamento que fez para a unidade

Basicamente preciso abrir o shapefile de lotes na intranet e acrescentar dados conforme solictado pelo sr. Bruno Carano. Os dados originais que precisam ser enriquecidos já foram subidos pelo sr. Bruno em uma pasta da intranet

In [56]:
import os
import pandas as pd
import geopandas as gpd
from utils.io.parquet import load_parquet

Abrindo arquivos

In [49]:
caminho_rede = r'\\sf_fs_cluster.sf.prefeitura.sp.gov.br\SF\SUREM\DECAD\DIMAP\DIMAP-1\Henrique\Lotes Fiscais'

In [50]:
os.listdir(caminho_rede)

['Lotes Fiscais.cpg',
 'Lotes Fiscais.dbf',
 'Lotes Fiscais.prj',
 'Lotes Fiscais.qmd',
 'Lotes Fiscais.shp',
 'Lotes Fiscais.shp.FEPF0724.14208.17120.sr.lock',
 'Lotes Fiscais.shp.FEPF0724.19884.17120.sr.lock',
 'Lotes Fiscais.shp.FEPF0724.19900.17120.sr.lock',
 'Lotes Fiscais.shp.FEPF0724.9996.17120.sr.lock',
 'Lotes Fiscais.shx']

In [51]:
fpath = os.path.join(caminho_rede, 'Lotes Fiscais.shp')
assert os.path.exists(fpath) and os.path.isfile(fpath), f"Arquivo não encontrado: {fpath}"

In [52]:
gdf = gpd.read_file(caminho_rede)

In [53]:
gdf.head()

,id,cod_id,cod_setor,tipo_qp,cod_qp,tipo_lote,cod_cond,cod_lote,cod_status,geometry
0,1.0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73..."
1,2.0,8897615,026,F,029,F,02,0000,1,"POLYGON ((336599.851 7396011.968, 336599.515 7..."
2,3.0,8897616,026,F,029,F,00,0004,1,"POLYGON ((336607.867 7396035.303, 336608.524 7..."
3,4.0,8897617,026,F,029,F,00,0005,1,"POLYGON ((336615.334 7396026.727, 336613.723 7..."
4,5.0,8897618,026,F,029,F,00,0030,1,"POLYGON ((336621.614 7395998.454, 336617.064 7..."

In [54]:
gdf.shape

(1692753, 10)

In [58]:
df = load_parquet('df_final_completo.parquet', subfolder='resultado_final', gdf=False, output=True)
df.head()

,id_lote,cd_setor_fiscal,cd_quadra_fiscal,cd_lote,cd_condominio,cd_tipo_lote,contribuinte_iptu,endereco,area_pol_lote,AC-1,...,ZM,ZMIS,ZMISa,ZMa,ZOE,ZPDS,ZPDSr,ZPI-1,ZPI-2,ZPR
0,210.008.0053-F.00,210,008,0053,00,F,210.008.0053-7,"R LUIS SALADIN, 187.0 - CID D'ABRIL, São Paul...",270.751684,0.0,...,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0
1,210.011.0047-F.00,210,011,0047,00,F,210.011.0047-4,"R MANUEL BENICIO, 257.0 - , São Paulo - SP. C...",176.359862,0.0,...,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0
2,210.016.0099-F.00,210,016,0099,00,F,210.016.0099-1,"R PERA-MARMELO, 472.0 - CID D ABRIL, São Paul...",150.331192,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,210.011.0087-F.00,210,011,0087,00,F,210.011.0087-3,"R MICAELA ALEGRIA, 70.0 - CID D ABRIL, São Pa...",145.726729,0.0,...,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0
4,210.008.0110-F.00,210,008,0110,00,F,210.008.0110-1,"R SIMAO MAYER, 117.0 - CID D ABRIL, São Paulo...",161.244863,0.0,...,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0

Interessante que só tem um registor que tem o contribuinte do IPTU duplicado e no caso dele há de faot dois registros com os códigos das quadras diferentes. Mas a área de polígono do lote é a mesma. E o endereço também, então vou deletar um deles para não dar mais duplicatas.

In [62]:
df[(df['contribuinte_iptu'].notnull())&(df['contribuinte_iptu'].duplicated(keep=False))]

,id_lote,cd_setor_fiscal,cd_quadra_fiscal,cd_lote,cd_condominio,cd_tipo_lote,contribuinte_iptu,endereco,area_pol_lote,AC-1,...,ZM,ZMIS,ZMISa,ZMa,ZOE,ZPDS,ZPDSr,ZPI-1,ZPI-2,ZPR
2616840,190.030.0005-F.00,190,030,0005,00,F,190.030.0005-1,"R TEODORO RODRIGUES, 92.0 - ILU, São Paulo - ...",232.211496,0.0,...,0.0,0.0,0.0,82.3852,0.0,0.0,0.0,0.0,0.0,0.0
2618609,190.030.0005-F.00,190,30,0005,00,F,190.030.0005-1,"R TEODORO RODRIGUES, 92.0 - ILU, São Paulo - ...",232.211496,0.0,...,0.0,0.0,0.0,82.3852,0.0,0.0,0.0,0.0,0.0,0.0

In [64]:
df[(df['contribuinte_iptu'].notnull())&(df['contribuinte_iptu'].duplicated(keep=False))][['id_lote', 'contribuinte_iptu', 'endereco', 'area_pol_lote']]

,id_lote,contribuinte_iptu,endereco,area_pol_lote
2616840,190.030.0005-F.00,190.030.0005-1,"R TEODORO RODRIGUES, 92.0 - ILU, São Paulo - ...",232.211496
2618609,190.030.0005-F.00,190.030.0005-1,"R TEODORO RODRIGUES, 92.0 - ILU, São Paulo - ...",232.211496

In [65]:
df.loc[2616840]['endereco']

'R  TEODORO RODRIGUES, 92.0 - ILU, São Paulo - SP. CEP: 02989-070'

In [66]:
df.loc[2618609]['endereco']

'R  TEODORO RODRIGUES, 92.0 - ILU, São Paulo - SP. CEP: 02989-070'

In [67]:
df.drop(2618609, inplace=True)

Passo 1- criando coluna código no gdf:


1 - CODLSQ (campo tipo texto; 6 caracteres) = junção de código do logradouro + dígito do código do logradouro + setor + quadra  ... todos da tabela dado avaliativo

Nesse caso é mais simples porque nao requer join é só usar o próprio gdf.

In [68]:
gdf

,id,cod_id,cod_setor,tipo_qp,cod_qp,tipo_lote,cod_cond,cod_lote,cod_status,geometry
0,1.0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73..."
1,2.0,8897615,026,F,029,F,02,0000,1,"POLYGON ((336599.851 7396011.968, 336599.515 7..."
2,3.0,8897616,026,F,029,F,00,0004,1,"POLYGON ((336607.867 7396035.303, 336608.524 7..."
3,4.0,8897617,026,F,029,F,00,0005,1,"POLYGON ((336615.334 7396026.727, 336613.723 7..."
4,5.0,8897618,026,F,029,F,00,0030,1,"POLYGON ((336621.614 7395998.454, 336617.064 7..."
...,...,...,...,...,...,...,...,...,...,...
1692748,1692749.0,10979005,067,F,014,F,00,0282,1,"POLYGON ((337462.708 7404865.621, 337476.614 7..."
1692749,1692750.0,10979006,067,F,014,F,00,0280,1,"POLYGON ((337462.977 7404875.28, 337498.525 74..."
1692750,1692751.0,10979008,055,F,036,F,00,0024,1,"POLYGON ((343402.987 7394651.942, 343400.023 7..."
1692751,1692752.0,10979009,055,F,036,F,00,0141,1,"POLYGON ((343388.622 7394629.285, 343388.622 7..."
1692752,1692753.0,10979010,055,F,036,F,00,0140,1,"POLYGON ((343400.023 7394653.366, 343388.622 7..."