# Solicitação Dimap 1

#### **Solicitado por**: Bruno Carano

Será que você consegue me ajudar gerando mais 4 colunas adicionais nesse mesmo shape?

Seriam elas:

1 - CODLSQ (campo tipo texto; 6 caracteres) = junção de código do logradouro + dígito do código do logradouro + setor + quadra  ... todos da tabela dado avaliativo

2 - tp_uso_imovel : código de uso da tabela dado avaliativo

3 - tp_padrao_construcao : código de padrão construtivo da tabela dado avaliativo

4 - tp_zonauso: nesse colocar o código do tipo de zona de uso que predomina no lote, baseado no seu estudo do zoneamento que fez para a unidade

Basicamente preciso abrir o shapefile de lotes na intranet e acrescentar dados conforme solictado pelo sr. Bruno Carano. Os dados originais que precisam ser enriquecidos já foram subidos pelo sr. Bruno em uma pasta da intranet.

Segue detalhamento após reunião:
1. Esse dado vem da própria tabela de dado avaliativo, basta juntar os nomes das colunas. Pois é o codlog do logradouro que está registrado como o logradouro daquele lote, não todos os logradouros das quadras.
2. Aqui preciso calcular o uso predominante do imóvel. vou calcular duas versões, uma ponderada pela quantidade de unidades e outra pela área construída (para os casos em que há mais de um lote por terreno - i.e., os condomínios)
3. Aqui vale o mesmo para o item anterior.
4. Aqui tenho que juntar com o estudo que já fiz anteriormente.

In [44]:
import os
import pandas as pd
import geopandas as gpd
from utils.io.path import data_path
from utils.io.parquet import load_parquet, save_parquet

Abrindo arquivos

In [45]:
#caminho para rodar de casa com a rede montada
caminho_rede = r'/home/hpougy/Rede_DIMAP/Henrique'

def load_data(caminho_rede:str=caminho_rede)->tuple[gpd.GeoDataFrame, pd.DataFrame]:
    """
    Carrega os dados necessários para a análise.

    Args:
        caminho_rede (str): Caminho para a rede onde os dados estão armazenados.

    Returns:
        tuple[GeoDataFrame, DataFrame]: Um GeoDataFrame com os lotes fiscais e um DataFrame com os dados avaliativos.
    """


    fname_gpd_lotes = 'gpd_lotes.parquet'
    fpath_gpd_lotes = data_path(fname_gpd_lotes, 'dados_bruno')
    fname_dados_avaliativos = 'df_dados_avaliativos.parquet'
    fpath_df_dados_avaliativos = data_path(fname_dados_avaliativos, 'dados_bruno')

    if os.path.exists(fpath_gpd_lotes):
        print('Carregando GeoDataFrame dos lotes fiscais...')
        gpd_lotes = load_parquet(fname_gpd_lotes, subfolder='dados_bruno', gdf=True, output=False)

    else:
        print('Buscando os lotes fiscais na rede e salvando como parquet...')
        lotes = os.path.join(caminho_rede, 'Lotes Fiscais')
        gpd_lotes = gpd.read_file(lotes)
        save_parquet(gpd_lotes, fname_gpd_lotes, subfolder='dados_bruno', gdf=True, output=False)

    if os.path.exists(fpath_df_dados_avaliativos):
        print('Carregando DataFrame dos dados avaliativos...')
        df_dados_avaliativos = load_parquet(fname_dados_avaliativos, subfolder='dados_bruno', gdf=False, output=False)

    else:
        print('Buscando os dados avaliativos na rede e salvando como parquet...')
        colunas = [
            'cd_contribuinte',
            'cd_logradouro',
            'tp_terreno',
            'qt_esquina_imovel',
            'qt_area_terreno_imovel',
            'qt_testada_terreno_calculo',
            'cd_condominio_imovel',
            'nr_fracao_ideal_terreno',
            'qt_area_construida_total',
            'tp_padrao_construcao',
            'qt_area_ocupada',
            'qt_pavimento',
            'an_construcao_corrigido',
            'tp_uso_imovel',
            'tp_meio_cobranca_tributo',
            'cd_zona_fiscal',
            'qt_primeira_testada_imovel'
            ]
        dados_avaliativos = os.path.join(caminho_rede, 'dados_avaliativos.csv')
        df_dados_avaliativos = pd.read_csv(dados_avaliativos, sep=';', names=colunas, header=None)
        save_parquet(df_dados_avaliativos, fname_dados_avaliativos, subfolder='dados_bruno', gdf=False, output=False)

    return gpd_lotes, df_dados_avaliativos

In [46]:
gdf, df = load_data()

Carregando GeoDataFrame dos lotes fiscais...
Carregando DataFrame dos dados avaliativos...

In [47]:
gdf.head()

,id,cod_id,cod_setor,tipo_qp,cod_qp,tipo_lote,cod_cond,cod_lote,cod_status,geometry
0,1.0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73..."
1,2.0,8897615,026,F,029,F,02,0000,1,"POLYGON ((336599.851 7396011.968, 336599.515 7..."
2,3.0,8897616,026,F,029,F,00,0004,1,"POLYGON ((336607.867 7396035.303, 336608.524 7..."
3,4.0,8897617,026,F,029,F,00,0005,1,"POLYGON ((336615.334 7396026.727, 336613.723 7..."
4,5.0,8897618,026,F,029,F,00,0030,1,"POLYGON ((336621.614 7395998.454, 336617.064 7..."

In [48]:
gdf['cod_id'].duplicated().any()

np.False_

In [49]:
#deixando claro que é o feature id numérico (veio do parquet eu acho)
gdf.rename({'cod_id' : 'fid'}, axis=1, inplace=True)

In [50]:
#dropando a coluna de id
if 'id' in gdf.columns:
    gdf.drop('id', axis=1, inplace=True)

In [51]:
gdf.shape

(1692753, 9)

In [52]:
gdf['tipo_lote'].value_counts()

tipo_lote
F    1665031
M      16885
D       4902
V       3520
S       2399
W         13
E          3
Name: count, dtype: int64

In [53]:
# a base de lotes fiscais tem muitos tipos de lote, mas para o nosso caso só interessa os lotes do tipo 'F' (lotes fiscais)

gdf = gdf[gdf['tipo_lote']=='F'].reset_index(drop=True)

In [54]:
gdf.head()

,fid,cod_setor,tipo_qp,cod_qp,tipo_lote,cod_cond,cod_lote,cod_status,geometry
0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73..."
1,8897615,026,F,029,F,02,0000,1,"POLYGON ((336599.851 7396011.968, 336599.515 7..."
2,8897616,026,F,029,F,00,0004,1,"POLYGON ((336607.867 7396035.303, 336608.524 7..."
3,8897617,026,F,029,F,00,0005,1,"POLYGON ((336615.334 7396026.727, 336613.723 7..."
4,8897618,026,F,029,F,00,0030,1,"POLYGON ((336621.614 7395998.454, 336617.064 7..."

In [55]:
gdf.shape

(1665031, 9)

In [56]:
df.head()

,cd_contribuinte,cd_logradouro,tp_terreno,qt_esquina_imovel,qt_area_terreno_imovel,qt_testada_terreno_calculo,cd_condominio_imovel,nr_fracao_ideal_terreno,qt_area_construida_total,tp_padrao_construcao,qt_area_ocupada,qt_pavimento,an_construcao_corrigido,tp_uso_imovel,tp_meio_cobranca_tributo,cd_zona_fiscal,qt_primeira_testada_imovel
0,100300014,38121,2,1,136,13.00,0,0.0,135,32,108,1,1924,40,11,1,0
1,100300022,38121,1,0,90,6.00,0,0.0,67,32,67,1,1944,40,11,1,0
2,100300030,38121,1,0,105,7.85,0,0.0,140,32,84,2,1965,40,11,1,0
3,100300049,38121,1,0,108,6.05,0,0.0,103,32,86,1,1944,40,11,1,0
4,100300057,38121,1,0,120,6.70,0,0.0,170,32,110,2,2004,40,11,1,0

In [57]:
df.shape

(3955973, 17)

Como no final os dados seram feito join com a base geoespacial, e a base geoespacial representa os terrenos dos imóveis (ou seja, não tem a representação das unidades de condominios e apartamentos) será necessário usar agregações para representar os dados das unidades para todo o condomínio. Vide o exemplo do uso, para caso de prédios com uso misto, ou o exemplo do tipo de padrão de cosntrução, pois podem ter prédios com diferentes unidades.

Então a primeira coisa que precisamos fazer é criar o ID que permite o join da base de dado avaliativo (a nível de lote) com a base de dados geoespacial dos terrenos dos imóveis.

Esse ID é basicamente o código do setor + quadra + lote + codigo do condominio. Com a diferença que, no caso dos imóveis condominiais (ou seja, aqueles no qual o código do condomínio não é 00), o lote deve ser zerado, se tornando 0000. Isso porque o código de condominio identifica unicamente os condominios dentro de uma mesma quadra. Por exemplo se uma quadra tem tres condominios, um deles é o 01, o outro o 02, o outro o 03. Nunca haverão dois cd_condominio 01 numa mesma quadra (mas sempre podem haver muitos 00, que não são condominios.)

Começamos identificando os condominios na base de dado avaliativo

In [58]:
df['cd_condominio_imovel'].isnull().any()

np.False_

In [59]:
df['cd_condominio_imovel'].dtype

dtype('int64')

Temos duas pitadas de sal aqui:
1. a coluna veio como int quando deveria ser str (mas digit)
2. há casos com 3 dígitos. Como checado com a diretora Mariana, isso ocorre pois essa coluna veio com o dígito verificador do condomínio.

A solução é converter para string, fazer zfill com 0 à esquerda para 3 dígitos e remover o último dígito (correspondente ao dígito verificador)

In [60]:
df['cd_condominio_imovel'].astype(str).str.len().unique()

array([1, 2, 3])

In [61]:
df['cd_condominio_limpo'] = df['cd_condominio_imovel'].astype(str).str.zfill(3).str[:-1]

In [62]:
df['cd_condominio_limpo'].sample(3)

859927     00
1821763    00
921950     01
Name: cd_condominio_limpo, dtype: str

In [63]:
(df['cd_condominio_limpo'].str.len()==2).all()

np.True_

In [64]:
df['cd_condominio_limpo'].str.isdigit().all()

np.True_

In [65]:
df['is_condominio'] = df['cd_condominio_imovel']

A mesma coisa aconteceu com o código do contribuinte que veio como int. Tem que dar um zfill

In [66]:
df['cd_contribuinte'].dtype

dtype('int64')

In [67]:
df['cd_contribuinte'].astype(str).str.len().unique()

array([ 9, 10, 11])

O total deve ser 11:

* Setor: 3 digitos
* Quadra: 3 digitos
* Lote: 4 digitos
* Digito verificador: 1 digito

In [68]:
df['cd_contribuinte_limpo'] = df['cd_contribuinte'].astype(str).str.zfill(11)

In [69]:
df['cd_contribuinte_limpo'].str.isdigit().all()

np.True_

Com isso ele funciona como um id: sem duplicatas, no mesmo formato e sem nenhum vazio

In [70]:
df['cd_contribuinte_limpo'].notnull().all()

np.True_

In [71]:
df['cd_contribuinte_limpo'].duplicated().any()

np.False_

In [72]:
df['cd_contribuinte_limpo'].str.len().unique()

array([11])

Agora podemos extrair o "setor quadra lote"

In [73]:
df['setor'] = df['cd_contribuinte_limpo'].str[:3]
df['quadra'] = df['cd_contribuinte_limpo'].str[3:6]
df['lote'] = df['cd_contribuinte_limpo'].str[6:-1]

E calcular nosso indice

In [74]:
#basicamente coloca 0000 no lote quando o imovel é um condominio
df['lote_para_id'] = df.apply(lambda row: row['lote'] if not row['is_condominio'] else '0000', axis=1)

In [76]:
df['id_imovel']  = df['setor'] + '.' + df['quadra'] + '.' + df['lote_para_id'] + '-' + df['cd_condominio_limpo']

In [77]:
df['id_imovel'].sample(5)

724260     033.023.0000-13
1523148    068.025.0192-00
95345      006.024.0000-05
2346449    107.065.0033-00
1638574    071.440.0000-03
Name: id_imovel, dtype: str

Checango abaixo se todos os casos de duplicatas são condominios

In [82]:
ids_duplicados = df[df['id_imovel'].duplicated(keep=False)]
assert (ids_duplicados['cd_condominio_limpo']!='00').all()
assert ids_duplicados['is_condominio'].all() 

del ids_duplicados