# Solicitação Dimap 1

#### **Solicitado por**: Bruno Carano

Será que você consegue me ajudar gerando mais 4 colunas adicionais nesse mesmo shape?

Seriam elas:

1 - CODLSQ (campo tipo texto; 6 caracteres) = junção de código do logradouro + dígito do código do logradouro + setor + quadra  ... todos da tabela dado avaliativo

2 - tp_uso_imovel : código de uso da tabela dado avaliativo

3 - tp_padrao_construcao : código de padrão construtivo da tabela dado avaliativo

4 - tp_zonauso: nesse colocar o código do tipo de zona de uso que predomina no lote, baseado no seu estudo do zoneamento que fez para a unidade

Basicamente preciso abrir o shapefile de lotes na intranet e acrescentar dados conforme solictado pelo sr. Bruno Carano. Os dados originais que precisam ser enriquecidos já foram subidos pelo sr. Bruno em uma pasta da intranet

In [46]:
import os
import pandas as pd
import geopandas as gpd
from utils.io.path import data_path
from utils.io.parquet import load_parquet, save_parquet

Abrindo arquivos

In [47]:
#caminho para rodar de casa com a rede montada
caminho_rede = r'/home/hpougy/Rede_DIMAP/Henrique'

def load_data(caminho_rede:str=caminho_rede)->tuple[gpd.GeoDataFrame, pd.DataFrame]:
    """
    Carrega os dados necessários para a análise.

    Args:
        caminho_rede (str): Caminho para a rede onde os dados estão armazenados.

    Returns:
        tuple[GeoDataFrame, DataFrame]: Um GeoDataFrame com os lotes fiscais e um DataFrame com os dados avaliativos.
    """


    fname_gpd_lotes = 'gpd_lotes.parquet'
    fpath_gpd_lotes = data_path(fname_gpd_lotes, 'dados_bruno')
    fname_dados_avaliativos = 'df_dados_avaliativos.parquet'
    fpath_df_dados_avaliativos = data_path(fname_dados_avaliativos, 'dados_bruno')

    if os.path.exists(fpath_gpd_lotes):
        print('Carregando GeoDataFrame dos lotes fiscais...')
        gpd_lotes = load_parquet(fname_gpd_lotes, subfolder='dados_bruno', gdf=True, output=False)

    else:
        print('Buscando os lotes fiscais na rede e salvando como parquet...')
        lotes = os.path.join(caminho_rede, 'Lotes Fiscais')
        gpd_lotes = gpd.read_file(lotes)
        save_parquet(gpd_lotes, fname_gpd_lotes, subfolder='dados_bruno', gdf=True, output=False)

    if os.path.exists(fpath_df_dados_avaliativos):
        print('Carregando DataFrame dos dados avaliativos...')
        df_dados_avaliativos = load_parquet(fname_dados_avaliativos, subfolder='dados_bruno', gdf=False, output=False)

    else:
        print('Buscando os dados avaliativos na rede e salvando como parquet...')
        colunas = [
            'cd_contribuinte',
            'cd_logradouro',
            'tp_terreno',
            'qt_esquina_imovel',
            'qt_area_terreno_imovel',
            'qt_testada_terreno_calculo',
            'cd_condominio_imovel',
            'nr_fracao_ideal_terreno',
            'qt_area_construida_total',
            'tp_padrao_construcao',
            'qt_area_ocupada',
            'qt_pavimento',
            'an_construcao_corrigido',
            'tp_uso_imovel',
            'tp_meio_cobranca_tributo',
            'cd_zona_fiscal',
            'qt_primeira_testada_imovel'
            ]
        dados_avaliativos = os.path.join(caminho_rede, 'dados_avaliativos.csv')
        df_dados_avaliativos = pd.read_csv(dados_avaliativos, sep=';', names=colunas, header=None)
        save_parquet(df_dados_avaliativos, fname_dados_avaliativos, subfolder='dados_bruno', gdf=False, output=False)

    return gpd_lotes, df_dados_avaliativos

In [48]:
gdf, df = load_data()

Carregando GeoDataFrame dos lotes fiscais...
Carregando DataFrame dos dados avaliativos...

In [49]:
gdf.head()

,id,cod_id,cod_setor,tipo_qp,cod_qp,tipo_lote,cod_cond,cod_lote,cod_status,geometry
0,1.0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73..."
1,2.0,8897615,026,F,029,F,02,0000,1,"POLYGON ((336599.851 7396011.968, 336599.515 7..."
2,3.0,8897616,026,F,029,F,00,0004,1,"POLYGON ((336607.867 7396035.303, 336608.524 7..."
3,4.0,8897617,026,F,029,F,00,0005,1,"POLYGON ((336615.334 7396026.727, 336613.723 7..."
4,5.0,8897618,026,F,029,F,00,0030,1,"POLYGON ((336621.614 7395998.454, 336617.064 7..."

In [50]:
gdf.shape

(1692753, 10)

In [51]:
df.head()

,cd_contribuinte,cd_logradouro,tp_terreno,qt_esquina_imovel,qt_area_terreno_imovel,qt_testada_terreno_calculo,cd_condominio_imovel,nr_fracao_ideal_terreno,qt_area_construida_total,tp_padrao_construcao,qt_area_ocupada,qt_pavimento,an_construcao_corrigido,tp_uso_imovel,tp_meio_cobranca_tributo,cd_zona_fiscal,qt_primeira_testada_imovel
0,100300014,38121,2,1,136,13.00,0,0.0,135,32,108,1,1924,40,11,1,0
1,100300022,38121,1,0,90,6.00,0,0.0,67,32,67,1,1944,40,11,1,0
2,100300030,38121,1,0,105,7.85,0,0.0,140,32,84,2,1965,40,11,1,0
3,100300049,38121,1,0,108,6.05,0,0.0,103,32,86,1,1944,40,11,1,0
4,100300057,38121,1,0,120,6.70,0,0.0,170,32,110,2,2004,40,11,1,0

In [52]:
df.shape

(3955973, 17)

Passo 1- criando coluna código no gdf:


1 - CODLSQ (campo tipo texto; 6 caracteres) = junção de código do logradouro + dígito do código do logradouro + setor + quadra  ... todos da tabela dado avaliativo

In [53]:
df.dtypes

cd_contribuinte                 int64
cd_logradouro                   int64
tp_terreno                      int64
qt_esquina_imovel               int64
qt_area_terreno_imovel          int64
qt_testada_terreno_calculo    float64
cd_condominio_imovel            int64
nr_fracao_ideal_terreno       float64
qt_area_construida_total        int64
tp_padrao_construcao            int64
qt_area_ocupada                 int64
qt_pavimento                    int64
an_construcao_corrigido         int64
tp_uso_imovel                   int64
tp_meio_cobranca_tributo        int64
cd_zona_fiscal                  int64
qt_primeira_testada_imovel      int64
dtype: object

In [54]:
# precisa dar zfill porque abriu como int o cd contribuinte
df['cd_contribuinte'] = df['cd_contribuinte'].astype(str).str.zfill(11)

In [55]:
df['cd_logradouro'] = df['cd_logradouro'].astype(str).str.zfill(6)

In [56]:
df['setor'] = df['cd_contribuinte'].str[:3]
df['quadra'] = df['cd_contribuinte'].str[3:6]

In [57]:
df['CODLSQ']= df['cd_logradouro'] + '.' + df['setor'] + '.' + df['quadra']

In [58]:
join_cod_logradouro_quadra = df[['CODLSQ', 'cd_logradouro', 'setor', 'quadra']].drop_duplicates()
join_cod_logradouro_quadra.head()

             CODLSQ cd_logradouro setor quadra
0    038121.001.003        038121   001    003
13   061565.001.003        061565   001    003
23   104850.001.003        104850   001    003
31   189936.001.003        189936   001    003
124  038121.001.004        038121   001    004

In [59]:
join_cod_logradouro_quadra['join_id'] = join_cod_logradouro_quadra['setor'] + '.' + join_cod_logradouro_quadra['quadra']

In [60]:
join_cod_logradouro_quadra.drop(['cd_logradouro', 'setor', 'quadra'], axis=1, inplace=True)

In [61]:
join_cod_logradouro_quadra.shape

(157090, 2)

In [62]:
join_cod_logradouro_quadra.duplicated().any()

np.False_

In [63]:
gdf['join_id'] = gdf['cod_setor'].str.zfill(3) + '.' + gdf['cod_qp'].str.zfill(3)

In [64]:
gdf.shape

(1692753, 11)

In [65]:
gdf = pd.merge(gdf, join_cod_logradouro_quadra, on='join_id', how='left')

In [66]:
gdf.shape

(7152014, 12)

In [67]:
gdf.head()

,id,cod_id,cod_setor,tipo_qp,cod_qp,tipo_lote,cod_cond,cod_lote,cod_status,geometry,join_id,CODLSQ
0,1.0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73...",026.029,047368.026.029
1,1.0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73...",026.029,106216.026.029
2,1.0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73...",026.029,096776.026.029
3,1.0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73...",026.029,043745.026.029
4,2.0,8897615,026,F,029,F,02,0000,1,"POLYGON ((336599.851 7396011.968, 336599.515 7...",026.029,047368.026.029

In [68]:
gdf['CODLSQ'].isnull().any()

np.True_

In [69]:
gdf['CODLSQ'].isnull().mean()

np.float64(0.00027265047299963337)

In [70]:
gdf['CODLSQ'].isnull().sum()

np.int64(1950)

In [71]:
gdf.drop(columns=['join_id'], inplace=True)

2 - tp_uso_imovel : código de uso da tabela dado avaliativo

In [72]:
df.head()

,cd_contribuinte,cd_logradouro,tp_terreno,qt_esquina_imovel,qt_area_terreno_imovel,qt_testada_terreno_calculo,cd_condominio_imovel,nr_fracao_ideal_terreno,qt_area_construida_total,tp_padrao_construcao,qt_area_ocupada,qt_pavimento,an_construcao_corrigido,tp_uso_imovel,tp_meio_cobranca_tributo,cd_zona_fiscal,qt_primeira_testada_imovel,setor,quadra,CODLSQ
0,00100300014,038121,2,1,136,13.00,0,0.0,135,32,108,1,1924,40,11,1,0,001,003,038121.001.003
1,00100300022,038121,1,0,90,6.00,0,0.0,67,32,67,1,1944,40,11,1,0,001,003,038121.001.003
2,00100300030,038121,1,0,105,7.85,0,0.0,140,32,84,2,1965,40,11,1,0,001,003,038121.001.003
3,00100300049,038121,1,0,108,6.05,0,0.0,103,32,86,1,1944,40,11,1,0,001,003,038121.001.003
4,00100300057,038121,1,0,120,6.70,0,0.0,170,32,110,2,2004,40,11,1,0,001,003,038121.001.003

In [73]:
coluna_interesse = 'tp_uso_imovel'

Nesse caso vai precisar separar condominio de nao condominio para fazer o join

In [74]:
df['cd_condominio_imovel'].isnull().any()

np.False_

In [75]:
df['cd_condominio_imovel'].astype(str).str.len().unique()

array([1, 2, 3])

Após conversa com a Mariana, diretora de DIMAP-1, chegamos a conclusao que o campo cd_condominio_imovel na verdade possui um digito verificador. E que no caso para poder fazer o join temos que tirar esse dígito, pois a outra base não contém digito no condomínio.

In [76]:
#aqui por exemplo é condominio 43 e digito 3
df['cd_condominio_imovel'].max()

np.int64(434)

In [77]:
df['cd_condominio_imovel'].isnull().any()

np.False_

In [78]:
df['cd_condominio_imovel'] = df['cd_condominio_imovel'].astype(str).str.zfill(3)

In [79]:
df['cd_condominio_imovel_limpo'] = df['cd_condominio_imovel'].str[:-1]

In [80]:
df['cd_condominio_imovel_limpo'].str.len().unique()

array([2])

In [81]:
df['is_condominio'] = df['cd_condominio_imovel']!='00'

In [82]:
def id_lote_cond(row):
    if not row['is_condominio']:
        #tem que retirar o dígito
        return row['cd_contribuinte'].str[:-1]+'.'+row['cd_condominio_imovel_limpo'].astype(str).str.zfill(2)
    else:
        contrib = row['cd_contribuinte']
        setor = contrib[:3]
        quadra = contrib[3:6]
        digito_sql = contrib[-1]
        contribuinte_formatado = setor+quadra+'0000' #aqui nao adiciona o digito de volta
        return contribuinte_formatado+'.'+row['cd_condominio_imovel_limpo'].zfill(2)

In [83]:
df.head()

,cd_contribuinte,cd_logradouro,tp_terreno,qt_esquina_imovel,qt_area_terreno_imovel,qt_testada_terreno_calculo,cd_condominio_imovel,nr_fracao_ideal_terreno,qt_area_construida_total,tp_padrao_construcao,...,an_construcao_corrigido,tp_uso_imovel,tp_meio_cobranca_tributo,cd_zona_fiscal,qt_primeira_testada_imovel,setor,quadra,CODLSQ,cd_condominio_imovel_limpo,is_condominio
0,00100300014,038121,2,1,136,13.00,000,0.0,135,32,...,1924,40,11,1,0,001,003,038121.001.003,00,True
1,00100300022,038121,1,0,90,6.00,000,0.0,67,32,...,1944,40,11,1,0,001,003,038121.001.003,00,True
2,00100300030,038121,1,0,105,7.85,000,0.0,140,32,...,1965,40,11,1,0,001,003,038121.001.003,00,True
3,00100300049,038121,1,0,108,6.05,000,0.0,103,32,...,1944,40,11,1,0,001,003,038121.001.003,00,True
4,00100300057,038121,1,0,120,6.70,000,0.0,170,32,...,2004,40,11,1,0,001,003,038121.001.003,00,True

In [84]:
df['id_lote_cond'] = df.apply(id_lote_cond, axis=1)

In [85]:
df['id_lote_cond'].sample(5)

205109     0090520000.07
1587431    0701060000.01
732282     0330390000.17
1723084    0760250000.01
3785502    2590090000.00
Name: id_lote_cond, dtype: str

In [86]:
gdf.head()

,id,cod_id,cod_setor,tipo_qp,cod_qp,tipo_lote,cod_cond,cod_lote,cod_status,geometry,CODLSQ
0,1.0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73...",047368.026.029
1,1.0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73...",106216.026.029
2,1.0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73...",096776.026.029
3,1.0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73...",043745.026.029
4,2.0,8897615,026,F,029,F,02,0000,1,"POLYGON ((336599.851 7396011.968, 336599.515 7...",047368.026.029

In [87]:
gdf['id_lote_cond'] = gdf['cod_setor'] + gdf['cod_qp'] + gdf['cod_lote'] + '.' + gdf['cod_cond']

In [88]:
gdf['id_lote_cond'].sample(5)

3028804    0913600028.00
1382008    0462020001.00
1211257    1191240038.00
5525568    1371180095.00
6283926    1461060043.00
Name: id_lote_cond, dtype: str

Agora o join vai mexer bastante no tamanho porque estamos adicionando os apartamentos.

In [89]:
gdf.shape

(7152014, 12)

In [90]:
df.shape

(3955973, 23)

In [93]:
df_join = df[['id_lote_cond', 'tp_uso_imovel', 'tp_padrao_construcao']]

In [94]:
gdf = pd.merge(gdf, df_join, on='id_lote_cond', how='left')

In [95]:
gdf.shape

(16702819, 14)

In [96]:
gdf['tp_uso_imovel'].isnull().mean()

np.float64(0.4183758442212659)

In [97]:
gdf.head()

,id,cod_id,cod_setor,tipo_qp,cod_qp,tipo_lote,cod_cond,cod_lote,cod_status,geometry,CODLSQ,id_lote_cond,tp_uso_imovel,tp_padrao_construcao
0,1.0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73...",047368.026.029,0260290000.01,41.0,42.0
1,1.0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73...",047368.026.029,0260290000.01,41.0,42.0
2,1.0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73...",047368.026.029,0260290000.01,41.0,42.0
3,1.0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73...",047368.026.029,0260290000.01,20.0,22.0
4,1.0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73...",047368.026.029,0260290000.01,20.0,22.0

In [98]:
type(gdf)

geopandas.geodataframe.GeoDataFrame

In [99]:
gdf.to_file('data/dados_bruno/dados_bruno_carano_brutos.gpkg', layer='lotes_fiscais_com_dados_avaliativos', driver='GPKG')

In [100]:
gdf.shape

(16702819, 14)