# Solicitação Dimap 1

#### **Solicitado por**: Bruno Carano

Será que você consegue me ajudar gerando mais 4 colunas adicionais nesse mesmo shape?

Seriam elas:

1 - CODLSQ (campo tipo texto; 6 caracteres) = junção de código do logradouro + dígito do código do logradouro + setor + quadra  ... todos da tabela dado avaliativo

2 - tp_uso_imovel : código de uso da tabela dado avaliativo

3 - tp_padrao_construcao : código de padrão construtivo da tabela dado avaliativo

4 - tp_zonauso: nesse colocar o código do tipo de zona de uso que predomina no lote, baseado no seu estudo do zoneamento que fez para a unidade

Basicamente preciso abrir o shapefile de lotes na intranet e acrescentar dados conforme solictado pelo sr. Bruno Carano. Os dados originais que precisam ser enriquecidos já foram subidos pelo sr. Bruno em uma pasta da intranet.

Segue detalhamento após reunião:
1. Esse dado vem da própria tabela de dado avaliativo, basta juntar os nomes das colunas. Pois é o codlog do logradouro que está registrado como o logradouro daquele lote, não todos os logradouros das quadras.
2. Aqui preciso calcular o uso predominante do imóvel. vou calcular duas versões, uma ponderada pela quantidade de unidades e outra pela área construída (para os casos em que há mais de um lote por terreno - i.e., os condomínios)
3. Aqui vale o mesmo para o item anterior.
4. Aqui tenho que juntar com o estudo que já fiz anteriormente.

In [1]:
import os
import pandas as pd
import geopandas as gpd
from utils.io.path import data_path
from utils.io.parquet import load_parquet, save_parquet

Abrindo arquivos

In [2]:
#caminho para rodar de casa com a rede montada
caminho_rede = r'/home/hpougy/Rede_DIMAP/Henrique'

def load_data(caminho_rede:str=caminho_rede)->tuple[gpd.GeoDataFrame, pd.DataFrame]:
    """
    Carrega os dados necessários para a análise.

    Args:
        caminho_rede (str): Caminho para a rede onde os dados estão armazenados.

    Returns:
        tuple[GeoDataFrame, DataFrame]: Um GeoDataFrame com os lotes fiscais e um DataFrame com os dados avaliativos.
    """


    fname_gpd_lotes = 'gpd_lotes.parquet'
    fpath_gpd_lotes = data_path(fname_gpd_lotes, 'dados_bruno')
    fname_dados_avaliativos = 'df_dados_avaliativos.parquet'
    fpath_df_dados_avaliativos = data_path(fname_dados_avaliativos, 'dados_bruno')

    if os.path.exists(fpath_gpd_lotes):
        print('Carregando GeoDataFrame dos lotes fiscais...')
        gpd_lotes = load_parquet(fname_gpd_lotes, subfolder='dados_bruno', gdf=True, output=False)

    else:
        print('Buscando os lotes fiscais na rede e salvando como parquet...')
        lotes = os.path.join(caminho_rede, 'Lotes Fiscais')
        gpd_lotes = gpd.read_file(lotes)
        save_parquet(gpd_lotes, fname_gpd_lotes, subfolder='dados_bruno', gdf=True, output=False)

    if os.path.exists(fpath_df_dados_avaliativos):
        print('Carregando DataFrame dos dados avaliativos...')
        df_dados_avaliativos = load_parquet(fname_dados_avaliativos, subfolder='dados_bruno', gdf=False, output=False)

    else:
        print('Buscando os dados avaliativos na rede e salvando como parquet...')
        colunas = [
            'cd_contribuinte',
            'cd_logradouro',
            'tp_terreno',
            'qt_esquina_imovel',
            'qt_area_terreno_imovel',
            'qt_testada_terreno_calculo',
            'cd_condominio_imovel',
            'nr_fracao_ideal_terreno',
            'qt_area_construida_total',
            'tp_padrao_construcao',
            'qt_area_ocupada',
            'qt_pavimento',
            'an_construcao_corrigido',
            'tp_uso_imovel',
            'tp_meio_cobranca_tributo',
            'cd_zona_fiscal',
            'qt_primeira_testada_imovel'
            ]
        dados_avaliativos = os.path.join(caminho_rede, 'dados_avaliativos.csv')
        df_dados_avaliativos = pd.read_csv(dados_avaliativos, sep=';', names=colunas, header=None)
        save_parquet(df_dados_avaliativos, fname_dados_avaliativos, subfolder='dados_bruno', gdf=False, output=False)

    return gpd_lotes, df_dados_avaliativos

In [3]:
gdf, df = load_data()

Carregando GeoDataFrame dos lotes fiscais...
Carregando DataFrame dos dados avaliativos...

In [4]:
gdf.head()

,id,cod_id,cod_setor,tipo_qp,cod_qp,tipo_lote,cod_cond,cod_lote,cod_status,geometry
0,1.0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73..."
1,2.0,8897615,026,F,029,F,02,0000,1,"POLYGON ((336599.851 7396011.968, 336599.515 7..."
2,3.0,8897616,026,F,029,F,00,0004,1,"POLYGON ((336607.867 7396035.303, 336608.524 7..."
3,4.0,8897617,026,F,029,F,00,0005,1,"POLYGON ((336615.334 7396026.727, 336613.723 7..."
4,5.0,8897618,026,F,029,F,00,0030,1,"POLYGON ((336621.614 7395998.454, 336617.064 7..."

In [5]:
gdf['cod_id'].duplicated().any()

np.False_

In [6]:
#deixando claro que é o feature id numérico (veio do parquet eu acho)
gdf.rename({'cod_id' : 'fid'}, axis=1, inplace=True)

In [7]:
#dropando a coluna de id
if 'id' in gdf.columns:
    gdf.drop('id', axis=1, inplace=True)

In [8]:
gdf.shape

(1692753, 9)

In [9]:
gdf['tipo_lote'].value_counts()

tipo_lote
F    1665031
M      16885
D       4902
V       3520
S       2399
W         13
E          3
Name: count, dtype: int64

In [10]:
# a base de lotes fiscais tem muitos tipos de lote, mas para o nosso caso só interessa os lotes do tipo 'F' (lotes fiscais)

gdf = gdf[gdf['tipo_lote']=='F'].reset_index(drop=True)

In [11]:
gdf.head()

,fid,cod_setor,tipo_qp,cod_qp,tipo_lote,cod_cond,cod_lote,cod_status,geometry
0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73..."
1,8897615,026,F,029,F,02,0000,1,"POLYGON ((336599.851 7396011.968, 336599.515 7..."
2,8897616,026,F,029,F,00,0004,1,"POLYGON ((336607.867 7396035.303, 336608.524 7..."
3,8897617,026,F,029,F,00,0005,1,"POLYGON ((336615.334 7396026.727, 336613.723 7..."
4,8897618,026,F,029,F,00,0030,1,"POLYGON ((336621.614 7395998.454, 336617.064 7..."

In [12]:
gdf.shape

(1665031, 9)

In [13]:
df.head()

,cd_contribuinte,cd_logradouro,tp_terreno,qt_esquina_imovel,qt_area_terreno_imovel,qt_testada_terreno_calculo,cd_condominio_imovel,nr_fracao_ideal_terreno,qt_area_construida_total,tp_padrao_construcao,qt_area_ocupada,qt_pavimento,an_construcao_corrigido,tp_uso_imovel,tp_meio_cobranca_tributo,cd_zona_fiscal,qt_primeira_testada_imovel
0,100300014,38121,2,1,136,13.00,0,0.0,135,32,108,1,1924,40,11,1,0
1,100300022,38121,1,0,90,6.00,0,0.0,67,32,67,1,1944,40,11,1,0
2,100300030,38121,1,0,105,7.85,0,0.0,140,32,84,2,1965,40,11,1,0
3,100300049,38121,1,0,108,6.05,0,0.0,103,32,86,1,1944,40,11,1,0
4,100300057,38121,1,0,120,6.70,0,0.0,170,32,110,2,2004,40,11,1,0

In [14]:
df.shape

(3955973, 17)

### ID do terreno do imóvel

Como no final os dados seram feito join com a base geoespacial, e a base geoespacial representa os terrenos dos imóveis (ou seja, não tem a representação das unidades de condominios e apartamentos) será necessário usar agregações para representar os dados das unidades para todo o condomínio. Vide o exemplo do uso, para caso de prédios com uso misto, ou o exemplo do tipo de padrão de cosntrução, pois podem ter prédios com diferentes unidades.

Então a primeira coisa que precisamos fazer é criar o ID que permite o join da base de dado avaliativo (a nível de lote) com a base de dados geoespacial dos terrenos dos imóveis.

Esse ID é basicamente o código do setor + quadra + lote + codigo do condominio. Com a diferença que, no caso dos imóveis condominiais (ou seja, aqueles no qual o código do condomínio não é 00), o lote deve ser zerado, se tornando 0000. Isso porque o código de condominio identifica unicamente os condominios dentro de uma mesma quadra. Por exemplo se uma quadra tem tres condominios, um deles é o 01, o outro o 02, o outro o 03. Nunca haverão dois cd_condominio 01 numa mesma quadra (mas sempre podem haver muitos 00, que não são condominios.)

Começamos identificando os condominios na base de dado avaliativo

In [15]:
df['cd_condominio_imovel'].isnull().any()

np.False_

In [16]:
df['cd_condominio_imovel'].dtype

dtype('int64')

Temos duas pitadas de sal aqui:
1. a coluna veio como int quando deveria ser str (mas digit)
2. há casos com 3 dígitos. Como checado com a diretora Mariana, isso ocorre pois essa coluna veio com o dígito verificador do condomínio.

A solução é converter para string, fazer zfill com 0 à esquerda para 3 dígitos e remover o último dígito (correspondente ao dígito verificador)

In [17]:
df['cd_condominio_imovel'].astype(str).str.len().unique()

array([1, 2, 3])

In [18]:
df['cd_condominio_limpo'] = df['cd_condominio_imovel'].astype(str).str.zfill(3).str[:-1]

In [19]:
df['cd_condominio_limpo'].sample(3)

2195288    00
1404078    00
2767850    00
Name: cd_condominio_limpo, dtype: str

In [20]:
(df['cd_condominio_limpo'].str.len()==2).all()

np.True_

In [21]:
df['cd_condominio_limpo'].str.isdigit().all()

np.True_

In [22]:
df['is_condominio'] = df['cd_condominio_limpo']!='00'

In [23]:
df[df['is_condominio']][['cd_contribuinte', 'cd_condominio_imovel', 'cd_condominio_limpo']].sample(5)

         cd_contribuinte  cd_condominio_imovel cd_condominio_limpo
210358         906317411                    19                  01
3396661      17331002375                    19                  01
638871        2802024760                   140                  14
3533974      19005500742                    19                  01
2230701       9803402552                    19                  01

A mesma coisa aconteceu com o código do contribuinte que veio como int. Tem que dar um zfill

In [24]:
df['cd_contribuinte'].dtype

dtype('int64')

In [25]:
df['cd_contribuinte'].astype(str).str.len().unique()

array([ 9, 10, 11])

O total deve ser 11:

* Setor: 3 digitos
* Quadra: 3 digitos
* Lote: 4 digitos
* Digito verificador: 1 digito

In [26]:
df['cd_contribuinte_limpo'] = df['cd_contribuinte'].astype(str).str.zfill(11)

In [27]:
df['cd_contribuinte_limpo'].str.isdigit().all()

np.True_

Com isso ele funciona como um id: sem duplicatas, no mesmo formato e sem nenhum vazio

In [28]:
df['cd_contribuinte_limpo'].notnull().all()

np.True_

In [29]:
df['cd_contribuinte_limpo'].duplicated().any()

np.False_

In [30]:
df['cd_contribuinte_limpo'].str.len().unique()

array([11])

Agora podemos extrair o "setor quadra lote"

In [31]:
df['setor'] = df['cd_contribuinte_limpo'].str[:3]
df['quadra'] = df['cd_contribuinte_limpo'].str[3:6]
df['lote'] = df['cd_contribuinte_limpo'].str[6:-1]

E calcular nosso indice

In [32]:
#basicamente coloca 0000 no lote quando o imovel é um condominio
df['lote_para_id'] = df.apply(lambda row: row['lote'] if not row['is_condominio'] else '0000', axis=1)

In [33]:
df['id_imovel']  = df['setor'] + '.' + df['quadra'] + '.' + df['lote_para_id'] + '-' + df['cd_condominio_limpo']

In [34]:
df['id_imovel'].sample(5)

3052646    154.108.0061-00
287850     010.083.0000-07
2942207    147.043.0014-00
3228417    166.056.0009-00
3083580    156.014.0014-00
Name: id_imovel, dtype: str

Checango abaixo se todos os casos de duplicatas são condominios

In [35]:
ids_duplicados = df[df['id_imovel'].duplicated(keep=False)]
assert (ids_duplicados['cd_condominio_limpo']!='00').all()
assert ids_duplicados['is_condominio'].all() 

del ids_duplicados

### Calculo do CODLSQ - codlog por imovel com setor e quadra

Agora podemos calcular o primeiro item do pedido do Bruno, o CODLSQ

Mas temos que atentar para duas coisas:

1. o fato de que alguns condominios podem ter mais de um logradouro de referencia.
2. a coluna de código do logradouro pode estar como inteiro também

In [36]:
df['cd_logradouro'].dtype

dtype('int64')

In [37]:
df['cd_logradouro'].astype(str).str.len().unique()

array([5, 6, 4, 3, 2])

O CODLOG tem que ter 6 dígitos

In [38]:
df['codlog_limpo'] = df['cd_logradouro'].astype(str).str.zfill(6)

In [39]:
assert df['codlog_limpo'].str.isdigit().all()
assert df['codlog_limpo'].str.len().unique()==[6]

Como vemos abaixo, temos alguns casos em que um mesmo condominio (por ser muito grande talvez) tem mais de um codlog de referencia

In [40]:
codlogs_por_imovel = df.groupby('id_imovel')['codlog_limpo'].nunique().reset_index()
codlogs_por_imovel.rename({'codlog_limpo':'qt_codlog_limpo'}, axis=1, inplace=True)
codlogs_por_imovel.sort_values('qt_codlog_limpo', ascending=False).head()

               id_imovel  qt_codlog_limpo
462235   071.431.0000-01                8
1343057  168.256.0000-01                5
563240   082.607.0000-01                4
600358   087.473.0000-01                4
415708   068.226.0000-01                4

In [41]:
df[df['id_imovel']=='071.431.0000-01'].sample(5)

,cd_contribuinte,cd_logradouro,tp_terreno,qt_esquina_imovel,qt_area_terreno_imovel,qt_testada_terreno_calculo,cd_condominio_imovel,nr_fracao_ideal_terreno,qt_area_construida_total,tp_padrao_construcao,...,qt_primeira_testada_imovel,cd_condominio_limpo,is_condominio,cd_contribuinte_limpo,setor,quadra,lote,lote_para_id,id_imovel,codlog_limpo
1634257,7143101761,213942,2,9,53520,0.0,19,0.0014,92,22,...,0,01,True,07143101761,071,431,0176,0000,071.431.0000-01,213942
1634280,7143101990,213942,2,9,53520,0.0,19,0.0012,79,22,...,0,01,True,07143101990,071,431,0199,0000,071.431.0000-01,213942
1634339,7143102581,213942,2,9,53520,0.0,19,0.0012,79,22,...,0,01,True,07143102581,071,431,0258,0000,071.431.0000-01,213942
1634447,7143103667,214523,2,9,53520,0.0,19,0.0014,92,22,...,0,01,True,07143103667,071,431,0366,0000,071.431.0000-01,214523
1634866,7143107859,217832,2,9,53520,0.0,19,0.0012,79,22,...,0,01,True,07143107859,071,431,0785,0000,071.431.0000-01,217832

In [42]:
df[df['id_imovel']=='071.431.0000-01']['codlog_limpo'].unique()

<ArrowStringArray>
['214086', '213942', '214230', '214523', '221171', '220566', '217700',
 '217832']
Length: 8, dtype: str

In [43]:
codlogs_por_imovel = df.groupby(['id_imovel', 'codlog_limpo']).size().reset_index(name='count').sort_values(by='count', ascending=False)

In [44]:
codlogs_por_imovel.head()

               id_imovel codlog_limpo  count
714738   103.025.0000-01       133574   3985
1347691  169.009.0000-01       099490   2861
533631   078.351.0000-02       168386   2828
1362850  171.177.0000-01       085871   2502
1415852  176.164.0000-01       640590   1945

Agora vou obter a proporcao do codlog mais comum para cada imovel (e o codlog mais comum)

In [45]:
codlogs_por_imovel['total_codlogs_por_imovel'] = codlogs_por_imovel.groupby('id_imovel')['count'].transform('sum')

In [46]:
#só checando aqui tem que ter casos que a contagem é diferente do total e esses casos tem que ser condominio
checagem = codlogs_por_imovel['count']!=codlogs_por_imovel['total_codlogs_por_imovel']
codlogs_por_imovel[checagem].head()

              id_imovel codlog_limpo  count  total_codlogs_por_imovel
581109  085.591.0000-02       062383   1527                      1528
11092   006.064.0000-06       092762   1434                      1436
20864   010.068.0000-01       156566   1269                      1303
563680  082.528.0000-01       602515   1201                      1202
739667  107.075.0000-01       677698   1196                      1664

In [47]:
#checa se é todo mundo condominio
assert (codlogs_por_imovel[checagem]['id_imovel'].str[-7:-3]=="0000").all()
assert (codlogs_por_imovel[checagem]['id_imovel'].str[-2:]!="00").all()

In [48]:
codlogs_por_imovel['proporcao'] = codlogs_por_imovel['count'] / codlogs_por_imovel['total_codlogs_por_imovel']
codlogs_por_imovel['proporcao'] = codlogs_por_imovel['proporcao'].round(2)

In [49]:
codlogs_por_imovel.head()

,id_imovel,codlog_limpo,count,total_codlogs_por_imovel,proporcao
714738,103.025.0000-01,133574,3985,3985,1.0
1347691,169.009.0000-01,099490,2861,2861,1.0
533631,078.351.0000-02,168386,2828,2828,1.0
1362850,171.177.0000-01,085871,2502,2502,1.0
1415852,176.164.0000-01,640590,1945,1945,1.0

In [50]:
codlogs_por_imovel['proporcao'].value_counts()

proporcao
1.00    1676862
0.50        243
0.01        115
0.02        112
0.33        109
         ...
0.32          4
0.36          4
0.81          4
0.42          3
0.58          1
Name: count, Length: 101, dtype: int64

Agora vou ordenar pelo id do imovel e pela proporcao. E aí vou ficar apenas com a primeira linha para cada id imovel (ou seja, a qeu tem a maior proporcao)

In [51]:
codlogs_por_imovel.sort_values(by=['id_imovel', 'proporcao'], ascending=[True, False], inplace=True)

In [52]:
codlog_prevalente = codlogs_por_imovel.drop_duplicates(subset=['id_imovel'], keep='first')[['id_imovel', 'codlog_limpo', 'proporcao']]
codlog_prevalente.head()

         id_imovel codlog_limpo  proporcao
0  001.003.0000-01       061565       1.00
1  001.003.0000-02       189936       1.00
2  001.003.0000-03       104850       0.69
4  001.003.0000-04       061565       1.00
5  001.003.0001-00       038121       1.00

In [53]:
codlog_prevalente['proporcao'].value_counts()

proporcao
1.00    1676862
0.50        124
0.99        105
0.98         95
0.67         92
         ...
0.58          1
0.18          1
0.29          1
0.30          1
0.38          1
Name: count, Length: 63, dtype: int64

In [54]:
codlog_prevalente.rename({'codlog_limpo':'codlog_prevalente_unidade', 'proporcao':'codlog_prevalente_proporcao_por_unidade'}, axis=1, inplace=True)

### ID imovel no GeoDataFrame

Agora eu preciso juntar esses dados com o geodataframe. Porque ele que vai ser nosso dataframe de referencia final

In [55]:
gdf.head()

,fid,cod_setor,tipo_qp,cod_qp,tipo_lote,cod_cond,cod_lote,cod_status,geometry
0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73..."
1,8897615,026,F,029,F,02,0000,1,"POLYGON ((336599.851 7396011.968, 336599.515 7..."
2,8897616,026,F,029,F,00,0004,1,"POLYGON ((336607.867 7396035.303, 336608.524 7..."
3,8897617,026,F,029,F,00,0005,1,"POLYGON ((336615.334 7396026.727, 336613.723 7..."
4,8897618,026,F,029,F,00,0030,1,"POLYGON ((336621.614 7395998.454, 336617.064 7..."

In [56]:
#certificando qeu são só lotes fiscais
assert gdf['tipo_qp'].unique()==['F']
assert gdf['tipo_lote'].unique()==['F']

Ceritifcando se as colunas do indice estao ok ou se preicsam de limpeza

No caso do setor está tudo ok

In [57]:
assert gdf['cod_setor'].str.len().unique()==[3]
assert gdf['cod_setor'].str.isdigit().all()
assert gdf['cod_setor'].notnull().all()

No caso da quadra temos tamanhos diferentes. Vou ter que dar zfill

In [58]:
gdf['cod_qp'].str.len().unique()

array([3, 2])

In [59]:
assert gdf['cod_qp'].str.isdigit().all()
assert gdf['cod_qp'].notnull().all()

In [60]:
gdf[gdf['cod_qp'].str.len()!=3]['cod_qp'].unique()

<ArrowStringArray>
['36', '33', '30']
Length: 3, dtype: str

In [61]:
gdf['cod_quadra_limpo'] = gdf['cod_qp'].str.zfill(3)

In [62]:
assert gdf['cod_quadra_limpo'].str.isdigit().all()
assert gdf['cod_quadra_limpo'].notnull().all()
assert gdf['cod_quadra_limpo'].str.len().unique()==[3]

No lote é a mesma coisa

In [63]:
gdf['cod_lote'].str.len().unique()

array([4, 3])

In [64]:
assert gdf['cod_lote'].str.isdigit().all()
assert gdf['cod_lote'].notnull().all()

In [65]:
gdf[gdf['cod_lote'].str.len()!=3]['cod_qp'].unique()

<ArrowStringArray>
['029', '023', '022', '058', '348', '007', '263', '019', '026', '034',
 ...
 '847', '841', '712', '842', '829',  '36',  '33', '849', '994',  '30']
Length: 866, dtype: str

In [66]:
gdf['cod_lote_limpo'] = gdf['cod_lote'].str.zfill(4)

In [67]:
assert gdf['cod_lote_limpo'].str.isdigit().all()
assert gdf['cod_lote_limpo'].notnull().all()
assert gdf['cod_lote_limpo'].str.len().unique()==[4]

In [68]:
assert gdf['cod_cond'].str.len().unique()==[2]
assert gdf['cod_cond'].str.isdigit().all()
assert gdf['cod_cond'].notnull().all()

In [69]:
gdf['id_imovel'] = gdf['cod_setor'] + '.' + gdf['cod_quadra_limpo'] + '.' + gdf['cod_lote_limpo'] + '-' + gdf['cod_cond']

Menos de 1% (0.7%) dos poligonos não estão presentes na base de dados avaliativos

In [70]:
nao_encontrados_gdf = set(gdf['id_imovel']) -(set(df['id_imovel']))

In [71]:
len(nao_encontrados_gdf)

12864

In [72]:
len(nao_encontrados_gdf)/gdf['id_imovel'].nunique()

0.007725991559306174

E um pouco mais de 1% (1.5%) dos imóveis da base de dados avaliativos não tem contrapartida no GeoDataFrame (isso é, os polígonos de lotes)

In [73]:
nao_encontrados_df = set(df['id_imovel']) -(set(gdf['id_imovel']))

In [74]:
len(nao_encontrados_df)

26163

In [75]:
len(nao_encontrados_df)/df['id_imovel'].nunique()

0.01558872878245492

Join para dados finais

In [76]:
codlog_prevalente.head()

,id_imovel,codlog_prevalente_unidade,codlog_prevalente_proporcao_por_unidade
0,001.003.0000-01,061565,1.00
1,001.003.0000-02,189936,1.00
2,001.003.0000-03,104850,0.69
4,001.003.0000-04,061565,1.00
5,001.003.0001-00,038121,1.00

In [77]:
gdf.columns

Index(['fid', 'cod_setor', 'tipo_qp', 'cod_qp', 'tipo_lote', 'cod_cond',
       'cod_lote', 'cod_status', 'geometry', 'cod_quadra_limpo',
       'cod_lote_limpo', 'id_imovel'],
      dtype='str')

In [78]:
dados_finais = gdf.copy(deep=True)

dados_finais.drop(['cod_quadra_limpo', 'cod_lote_limpo'], axis=1, inplace=True)

In [79]:
dados_finais.head()

,fid,cod_setor,tipo_qp,cod_qp,tipo_lote,cod_cond,cod_lote,cod_status,geometry,id_imovel
0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73...",026.029.0000-01
1,8897615,026,F,029,F,02,0000,1,"POLYGON ((336599.851 7396011.968, 336599.515 7...",026.029.0000-02
2,8897616,026,F,029,F,00,0004,1,"POLYGON ((336607.867 7396035.303, 336608.524 7...",026.029.0004-00
3,8897617,026,F,029,F,00,0005,1,"POLYGON ((336615.334 7396026.727, 336613.723 7...",026.029.0005-00
4,8897618,026,F,029,F,00,0030,1,"POLYGON ((336621.614 7395998.454, 336617.064 7...",026.029.0030-00

In [80]:
dados_finais = pd.merge(dados_finais, codlog_prevalente, on='id_imovel', how='left')

In [81]:
dados_finais.head()

,fid,cod_setor,tipo_qp,cod_qp,tipo_lote,cod_cond,cod_lote,cod_status,geometry,id_imovel,codlog_prevalente_unidade,codlog_prevalente_proporcao_por_unidade
0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73...",026.029.0000-01,047368,0.93
1,8897615,026,F,029,F,02,0000,1,"POLYGON ((336599.851 7396011.968, 336599.515 7...",026.029.0000-02,047368,1.00
2,8897616,026,F,029,F,00,0004,1,"POLYGON ((336607.867 7396035.303, 336608.524 7...",026.029.0004-00,047368,1.00
3,8897617,026,F,029,F,00,0005,1,"POLYGON ((336615.334 7396026.727, 336613.723 7...",026.029.0005-00,047368,1.00
4,8897618,026,F,029,F,00,0030,1,"POLYGON ((336621.614 7395998.454, 336617.064 7...",026.029.0030-00,047368,1.00

### Tipo de uso do imóvel

Agora vamos fazer a mesma lógica para o tipo de uso do imóvel.

Com a diferença de que, neste caso, calcularemos a proporcao por unidade e a proporção por area construída.

In [82]:
df.head()

,cd_contribuinte,cd_logradouro,tp_terreno,qt_esquina_imovel,qt_area_terreno_imovel,qt_testada_terreno_calculo,cd_condominio_imovel,nr_fracao_ideal_terreno,qt_area_construida_total,tp_padrao_construcao,...,qt_primeira_testada_imovel,cd_condominio_limpo,is_condominio,cd_contribuinte_limpo,setor,quadra,lote,lote_para_id,id_imovel,codlog_limpo
0,100300014,38121,2,1,136,13.00,0,0.0,135,32,...,0,00,False,00100300014,001,003,0001,0001,001.003.0001-00,038121
1,100300022,38121,1,0,90,6.00,0,0.0,67,32,...,0,00,False,00100300022,001,003,0002,0002,001.003.0002-00,038121
2,100300030,38121,1,0,105,7.85,0,0.0,140,32,...,0,00,False,00100300030,001,003,0003,0003,001.003.0003-00,038121
3,100300049,38121,1,0,108,6.05,0,0.0,103,32,...,0,00,False,00100300049,001,003,0004,0004,001.003.0004-00,038121
4,100300057,38121,1,0,120,6.70,0,0.0,170,32,...,0,00,False,00100300057,001,003,0005,0005,001.003.0005-00,038121

In [83]:
df.columns

Index(['cd_contribuinte', 'cd_logradouro', 'tp_terreno', 'qt_esquina_imovel',
       'qt_area_terreno_imovel', 'qt_testada_terreno_calculo',
       'cd_condominio_imovel', 'nr_fracao_ideal_terreno',
       'qt_area_construida_total', 'tp_padrao_construcao', 'qt_area_ocupada',
       'qt_pavimento', 'an_construcao_corrigido', 'tp_uso_imovel',
       'tp_meio_cobranca_tributo', 'cd_zona_fiscal',
       'qt_primeira_testada_imovel', 'cd_condominio_limpo', 'is_condominio',
       'cd_contribuinte_limpo', 'setor', 'quadra', 'lote', 'lote_para_id',
       'id_imovel', 'codlog_limpo'],
      dtype='str')

In [84]:

tipos_uso_por_imovel = df.groupby(['id_imovel', 'tp_uso_imovel']).size().reset_index(name='count').sort_values(by='count', ascending=False)
tipos_uso_por_imovel.head()

               id_imovel  tp_uso_imovel  count
727989   103.025.0000-01             23   3835
1361382  169.009.0000-01             20   2860
545163   078.351.0000-02             20   2826
1531023  196.018.0000-08             20   1792
1376688  171.177.0000-01             24   1701

In [85]:
tipos_uso_por_imovel['total_usos_por_imovel'] = tipos_uso_por_imovel.groupby('id_imovel')['count'].transform('sum')
tipos_uso_por_imovel['proporcao'] = tipos_uso_por_imovel['count'] / tipos_uso_por_imovel['total_usos_por_imovel']
tipos_uso_por_imovel['proporcao'] = tipos_uso_por_imovel['proporcao'].round(2)

In [86]:
tipos_uso_por_imovel.head()

,id_imovel,tp_uso_imovel,count,total_usos_por_imovel,proporcao
727989,103.025.0000-01,23,3835,3985,0.96
1361382,169.009.0000-01,20,2860,2861,1.00
545163,078.351.0000-02,20,2826,2828,1.00
1531023,196.018.0000-08,20,1792,1806,0.99
1376688,171.177.0000-01,24,1701,2502,0.68

In [87]:
tipos_uso_por_imovel.sort_values(by=['id_imovel', 'proporcao'], ascending=[True, False], inplace=True)
tipos_uso_por_imovel.drop_duplicates(subset=['id_imovel'], keep='first', inplace=True)
tipos_uso_por_imovel.head()

         id_imovel  tp_uso_imovel  count  total_usos_por_imovel  proporcao
0  001.003.0000-01             20     28                     37       0.76
3  001.003.0000-02             20      5                      6       0.83
5  001.003.0000-03             20      8                     13       0.62
7  001.003.0000-04             20     10                     12       0.83
9  001.003.0001-00             40      1                      1       1.00

In [88]:
tipos_uso_por_imovel = tipos_uso_por_imovel[['id_imovel', 'tp_uso_imovel', 'proporcao']]
tipos_uso_por_imovel.rename({'tp_uso_imovel':'tp_uso_prevalente_unidade', 'proporcao':'tp_uso_prevalente_proporcao_por_unidade'}, axis=1, inplace=True)

In [89]:
tipos_uso_por_imovel.head()

,id_imovel,tp_uso_prevalente_unidade,tp_uso_prevalente_proporcao_por_unidade
0,001.003.0000-01,20,0.76
3,001.003.0000-02,20,0.83
5,001.003.0000-03,20,0.62
7,001.003.0000-04,20,0.83
9,001.003.0001-00,40,1.00

In [90]:
dados_finais = pd.merge(dados_finais, tipos_uso_por_imovel, on='id_imovel', how='left')

In [91]:
dados_finais.head()

,fid,cod_setor,tipo_qp,cod_qp,tipo_lote,cod_cond,cod_lote,cod_status,geometry,id_imovel,codlog_prevalente_unidade,codlog_prevalente_proporcao_por_unidade,tp_uso_prevalente_unidade,tp_uso_prevalente_proporcao_por_unidade
0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73...",026.029.0000-01,047368,0.93,20.0,0.79
1,8897615,026,F,029,F,02,0000,1,"POLYGON ((336599.851 7396011.968, 336599.515 7...",026.029.0000-02,047368,1.00,41.0,0.50
2,8897616,026,F,029,F,00,0004,1,"POLYGON ((336607.867 7396035.303, 336608.524 7...",026.029.0004-00,047368,1.00,42.0,1.00
3,8897617,026,F,029,F,00,0005,1,"POLYGON ((336615.334 7396026.727, 336613.723 7...",026.029.0005-00,047368,1.00,42.0,1.00
4,8897618,026,F,029,F,00,0030,1,"POLYGON ((336621.614 7395998.454, 336617.064 7...",026.029.0030-00,047368,1.00,42.0,1.00

In [92]:
df.columns

Index(['cd_contribuinte', 'cd_logradouro', 'tp_terreno', 'qt_esquina_imovel',
       'qt_area_terreno_imovel', 'qt_testada_terreno_calculo',
       'cd_condominio_imovel', 'nr_fracao_ideal_terreno',
       'qt_area_construida_total', 'tp_padrao_construcao', 'qt_area_ocupada',
       'qt_pavimento', 'an_construcao_corrigido', 'tp_uso_imovel',
       'tp_meio_cobranca_tributo', 'cd_zona_fiscal',
       'qt_primeira_testada_imovel', 'cd_condominio_limpo', 'is_condominio',
       'cd_contribuinte_limpo', 'setor', 'quadra', 'lote', 'lote_para_id',
       'id_imovel', 'codlog_limpo'],
      dtype='str')

Olhando abaixo as colunas relacionadas a área (principalmente se analisarmos a fracao ideal em relacao à área de terreno), vemos que a coluna qt_area_ocupada deve representar a área do terreno que é ocupada pelo empreendimento, enquanto a área construida total se refere de fato à área construída da unidade. Vamos usar esse último valor

In [93]:
df[df['is_condominio']][['qt_area_ocupada', 'qt_area_construida_total', 'nr_fracao_ideal_terreno', 'qt_area_terreno_imovel']].sample(10)

,qt_area_ocupada,qt_area_construida_total,nr_fracao_ideal_terreno,qt_area_terreno_imovel
738042,180,147,0.0110,280
1663788,600,167,0.0278,847
2229662,4998,166,0.0045,12083
2016889,4419,56,0.0012,8861
1673117,1500,396,0.0428,2023
309394,600,360,0.0322,1431
866338,2869,136,0.0060,5427
1592584,1530,117,0.0065,2031
374771,971,253,0.0287,1094
76231,700,31,0.0031,870

In [109]:
df['qt_area_construida_total'].isnull().any()

np.False_

In [111]:
#pode ter área construída zero, porque existem imoveis que sao terrenos que estao na base
(df['qt_area_construida_total']==0).any()

np.True_

In [94]:
tipos_uso_por_imovel_area = df.groupby(['id_imovel', 'tp_uso_imovel'])['qt_area_construida_total'].sum().reset_index(name='area').sort_values(by='area', ascending=False)
tipos_uso_por_imovel_area.head()

               id_imovel  tp_uso_imovel    area
575591   082.517.0014-00             71  950328
1611281  248.261.0001-00             14  464200
1156224  147.001.0001-00             43  446777
593441   085.591.0000-02             30  436646
1126561  141.057.0014-00             14  400000

In [95]:
tipos_uso_por_imovel_area['total_usos_por_imovel'] = tipos_uso_por_imovel_area.groupby('id_imovel')['area'].transform('sum')
tipos_uso_por_imovel_area['proporcao'] = tipos_uso_por_imovel_area['area'] / tipos_uso_por_imovel_area['total_usos_por_imovel']
tipos_uso_por_imovel_area['proporcao'] = tipos_uso_por_imovel_area['proporcao'].round(2)

In [96]:
tipos_uso_por_imovel_area.head()

,id_imovel,tp_uso_imovel,area,total_usos_por_imovel,proporcao
575591,082.517.0014-00,71,950328,950328,1.00
1611281,248.261.0001-00,14,464200,464200,1.00
1156224,147.001.0001-00,43,446777,446777,1.00
593441,085.591.0000-02,30,436646,676187,0.65
1126561,141.057.0014-00,14,400000,400000,1.00

In [97]:
tipos_uso_por_imovel_area['proporcao'].value_counts()

proporcao
1.00    1571319
0.01       1188
0.02        920
0.00        820
0.99        792
         ...
0.45         76
0.55         74
0.41         70
0.40         68
0.60         65
Name: count, Length: 101, dtype: int64

In [98]:
tipos_uso_por_imovel_area.sort_values(by=['id_imovel', 'proporcao'], ascending=[True, False], inplace=True)
tipos_uso_por_imovel_area.drop_duplicates(subset=['id_imovel'], keep='first', inplace=True)
tipos_uso_por_imovel_area.head()

         id_imovel  tp_uso_imovel  area  total_usos_por_imovel  proporcao
0  001.003.0000-01             20  1628                   1915       0.85
3  001.003.0000-02             20   255                    312       0.82
5  001.003.0000-03             20   680                   1044       0.65
7  001.003.0000-04             20  1063                   1393       0.76
9  001.003.0001-00             40   135                    135       1.00

In [99]:
tipos_uso_por_imovel_area = tipos_uso_por_imovel_area[['id_imovel', 'tp_uso_imovel', 'proporcao']]
tipos_uso_por_imovel_area.rename({'tp_uso_imovel':'tp_uso_prevalente_area', 'proporcao':'tp_uso_prevalente_proporcao_por_area'}, axis=1, inplace=True)
tipos_uso_por_imovel_area.head()

,id_imovel,tp_uso_prevalente_area,tp_uso_prevalente_proporcao_por_area
0,001.003.0000-01,20,0.85
3,001.003.0000-02,20,0.82
5,001.003.0000-03,20,0.65
7,001.003.0000-04,20,0.76
9,001.003.0001-00,40,1.00

In [ ]:
dados_finais = pd.merge(dados_finais, tipos_uso_por_imovel_area, on='id_imovel', how='left')

In [101]:
dados_finais.head()

,fid,cod_setor,tipo_qp,cod_qp,tipo_lote,cod_cond,cod_lote,cod_status,geometry,id_imovel,codlog_prevalente_unidade,codlog_prevalente_proporcao_por_unidade,tp_uso_prevalente_unidade,tp_uso_prevalente_proporcao_por_unidade,tp_uso_prevalente_area,tp_uso_prevalente_proporcao_por_area
0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73...",026.029.0000-01,047368,0.93,20.0,0.79,20.0,0.75
1,8897615,026,F,029,F,02,0000,1,"POLYGON ((336599.851 7396011.968, 336599.515 7...",026.029.0000-02,047368,1.00,41.0,0.50,41.0,0.50
2,8897616,026,F,029,F,00,0004,1,"POLYGON ((336607.867 7396035.303, 336608.524 7...",026.029.0004-00,047368,1.00,42.0,1.00,42.0,1.00
3,8897617,026,F,029,F,00,0005,1,"POLYGON ((336615.334 7396026.727, 336613.723 7...",026.029.0005-00,047368,1.00,42.0,1.00,42.0,1.00
4,8897618,026,F,029,F,00,0030,1,"POLYGON ((336621.614 7395998.454, 336617.064 7...",026.029.0030-00,047368,1.00,42.0,1.00,42.0,1.00

### Tipo de padrão da construção

Agora vamos fazer a mesma coisa para o padrão da construção - por unidade e por área construída.

In [102]:
padrao_constru_por_imovel = df.groupby(['id_imovel', 'tp_padrao_construcao']).size().reset_index(name='count').sort_values(by='count', ascending=False)
padrao_constru_por_imovel['total_padrao_construcao_por_imovel'] = padrao_constru_por_imovel.groupby('id_imovel')['count'].transform('sum')
padrao_constru_por_imovel['proporcao'] = padrao_constru_por_imovel['count'] / padrao_constru_por_imovel['total_padrao_construcao_por_imovel']
padrao_constru_por_imovel['proporcao'] = padrao_constru_por_imovel['proporcao'].round(2)

In [103]:
padrao_constru_por_imovel['proporcao'].value_counts()

proporcao
1.00    1669296
0.50        868
0.01        779
0.02        778
0.06        684
         ...
0.42         14
0.61         14
0.66         13
0.32         11
0.51         10
Name: count, Length: 101, dtype: int64

In [104]:
padrao_constru_por_imovel.sort_values(by=['id_imovel', 'proporcao'], ascending=[True, False], inplace=True)
padrao_constru_por_imovel.drop_duplicates(subset=['id_imovel'], keep='first', inplace=True)
padrao_constru_por_imovel = padrao_constru_por_imovel[['id_imovel', 'tp_padrao_construcao', 'proporcao']]
padrao_constru_por_imovel.rename({'tp_padrao_construcao':'tp_padrao_construcao_prevalente_unidade', 'proporcao':'tp_padrao_construcao_prevalente_proporcao_por_unidade'}, axis=1, inplace=True)
padrao_constru_por_imovel.sample(5)

,id_imovel,tp_padrao_construcao_prevalente_unidade,tp_padrao_construcao_prevalente_proporcao_por_unidade
666459,094.112.0024-00,10,1.0
406749,067.330.0279-00,12,1.0
1424189,177.019.0007-00,12,1.0
276690,055.226.0063-00,12,1.0
140652,039.140.0000-01,22,1.0

In [105]:
dados_finais = pd.merge(dados_finais, padrao_constru_por_imovel, on='id_imovel', how='left')

In [106]:
padrao_constru_por_area = df.groupby(['id_imovel', 'tp_padrao_construcao'])['qt_area_construida_total'].sum().reset_index(name='area').sort_values(by='area', ascending=False)
padrao_constru_por_area['total_padrao_construcao_por_area'] = padrao_constru_por_area.groupby('id_imovel')['area'].transform('sum')
padrao_constru_por_area['proporcao'] = padrao_constru_por_area['area'] / padrao_constru_por_area['total_padrao_construcao_por_area']
padrao_constru_por_area['proporcao'] = padrao_constru_por_area['proporcao'].round(2)

In [107]:
padrao_constru_por_area['proporcao'].value_counts()

proporcao
1.00    1574953
0.10        523
0.90        479
0.11        470
0.89        455
         ...
0.39         66
0.60         58
0.40         57
0.41         55
0.59         53
Name: count, Length: 101, dtype: int64

Note o NaN abaixo na proporcao, porque nesse caos é um terreno (padrao 0 é terreno e nao tem árera construida, aí dá dividido por 0)

In [108]:
padrao_constru_por_area.sort_values(by=['id_imovel', 'proporcao'], ascending=[True, False], inplace=True)
padrao_constru_por_area.drop_duplicates(subset=['id_imovel'], keep='first', inplace=True)
padrao_constru_por_area = padrao_constru_por_area[['id_imovel', 'tp_padrao_construcao', 'proporcao']]
padrao_constru_por_area.rename({'tp_padrao_construcao':'tp_padrao_construcao_prevalente_por_area', 'proporcao':'tp_padrao_construcao_prevalente_proporcao_por_area'}, axis=1, inplace=True)
padrao_constru_por_area.sample(5)

,id_imovel,tp_padrao_construcao_prevalente_por_area,tp_padrao_construcao_prevalente_proporcao_por_area
1073738,136.015.0038-00,0,NaN
710923,101.538.0063-00,10,1.0
319397,059.250.0046-00,11,1.0
1563268,227.086.0052-00,11,1.0
551502,080.047.0012-00,11,1.0

In [112]:
dados_finais = pd.merge(dados_finais, padrao_constru_por_area, on='id_imovel', how='left')

Agora precisamos só olhar a questão do Nan da proporcao por area (que acontece quando nao tem área construida)

In [113]:
dados_finais.head()

,fid,cod_setor,tipo_qp,cod_qp,tipo_lote,cod_cond,cod_lote,cod_status,geometry,id_imovel,codlog_prevalente_unidade,codlog_prevalente_proporcao_por_unidade,tp_uso_prevalente_unidade,tp_uso_prevalente_proporcao_por_unidade,tp_uso_prevalente_area,tp_uso_prevalente_proporcao_por_area,tp_padrao_construcao_prevalente_unidade,tp_padrao_construcao_prevalente_proporcao_por_unidade,tp_padrao_construcao_prevalente_por_area,tp_padrao_construcao_prevalente_proporcao_por_area
0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73...",026.029.0000-01,047368,0.93,20.0,0.79,20.0,0.75,22.0,0.79,22.0,0.75
1,8897615,026,F,029,F,02,0000,1,"POLYGON ((336599.851 7396011.968, 336599.515 7...",026.029.0000-02,047368,1.00,41.0,0.50,41.0,0.50,42.0,0.50,42.0,0.50
2,8897616,026,F,029,F,00,0004,1,"POLYGON ((336607.867 7396035.303, 336608.524 7...",026.029.0004-00,047368,1.00,42.0,1.00,42.0,1.00,31.0,1.00,31.0,1.00
3,8897617,026,F,029,F,00,0005,1,"POLYGON ((336615.334 7396026.727, 336613.723 7...",026.029.0005-00,047368,1.00,42.0,1.00,42.0,1.00,32.0,1.00,32.0,1.00
4,8897618,026,F,029,F,00,0030,1,"POLYGON ((336621.614 7395998.454, 336617.064 7...",026.029.0030-00,047368,1.00,42.0,1.00,42.0,1.00,31.0,1.00,31.0,1.00

Note que 99% dos casos em que tem terreno vai dar nulo (porque os imoveis de terreno nao tem área construída) (é possível haver casos raros também de terrenos em condominios, por isso não dá 100%)

In [118]:
dados_finais[dados_finais['tp_padrao_construcao_prevalente_unidade']==0]['tp_padrao_construcao_prevalente_proporcao_por_area'].isnull().mean()

np.float64(0.999901166238387)

Note que os nulls sao na mesma proporcao quando olhamos o tipo de uso e nao o tipo de padrao

In [119]:
dados_finais[dados_finais['tp_padrao_construcao_prevalente_unidade']==0]['tp_uso_prevalente_proporcao_por_area'].isnull().mean()

np.float64(0.999901166238387)

Se a gente filtra pelo tipo de uso == 0 (terrenos), a proporcao vai pra 100%

In [123]:
dados_finais[dados_finais['tp_uso_prevalente_area']==0]['tp_uso_prevalente_proporcao_por_area'].isnull().all()

np.True_

In [124]:
dados_finais[dados_finais['tp_uso_prevalente_area']==0]['tp_padrao_construcao_prevalente_proporcao_por_area'].isnull().all()

np.True_

Vou preencher com 1. Porque se nao tem área construída a proporção de fato é 1 (p. ex., o imóvel é 100% de uso de terreno no padrão 0 que é para terreno...)

In [131]:
dados_finais['tp_padrao_construcao_prevalente_proporcao_por_area'] = dados_finais.apply(lambda row: 1 if row['tp_uso_prevalente_area']==0 else row['tp_padrao_construcao_prevalente_proporcao_por_area'], axis=1)
dados_finais['tp_uso_prevalente_proporcao_por_area'] = dados_finais.apply(lambda row: 1 if row['tp_uso_prevalente_area']==0 else row['tp_uso_prevalente_proporcao_por_area'], axis=1)

In [135]:
dados_finais['tp_padrao_construcao_prevalente_proporcao_por_area'].isnull().sum()

np.int64(12864)

In [136]:
dados_finais['tp_uso_prevalente_proporcao_por_area'].isnull().sum()

np.int64(12864)

Os últimos casos que restaram com nulo são os casos em que não conseguiu fazer match.

In [138]:
dados_finais[dados_finais['tp_uso_prevalente_proporcao_por_area'].isnull()].sample(5)

,fid,cod_setor,tipo_qp,cod_qp,tipo_lote,cod_cond,cod_lote,cod_status,geometry,id_imovel,codlog_prevalente_unidade,codlog_prevalente_proporcao_por_unidade,tp_uso_prevalente_unidade,tp_uso_prevalente_proporcao_por_unidade,tp_uso_prevalente_area,tp_uso_prevalente_proporcao_por_area,tp_padrao_construcao_prevalente_unidade,tp_padrao_construcao_prevalente_proporcao_por_unidade,tp_padrao_construcao_prevalente_por_area,tp_padrao_construcao_prevalente_proporcao_por_area
518381,9382126,078,F,359,F,00,0029,1,"POLYGON ((323400.268 7400655.664, 323402.307 7...",078.359.0029-00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1075014,10017195,111,F,320,F,00,0040,1,"POLYGON ((348776.845 7400694.05, 348772.657 74...",111.320.0040-00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
932594,9778202,169,F,199,F,00,0062,1,"POLYGON ((322537.382 7385481.201, 322543.093 7...",169.199.0062-00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1297998,10243043,152,F,229,F,00,0020,1,"POLYGON ((349605.802 7386449.073, 349605.856 7...",152.229.0020-00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
628269,9497272,113,F,109,F,00,0019,1,"POLYGON ((346247.442 7395391.587, 346224.073 7...",113.109.0019-00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Juncao dados de zoneamento

In [139]:
zoneamento = pd.read_parquet('output/resultado_final/df_final_completo.parquet')

In [140]:
zoneamento.head()

,id_lote,cd_setor_fiscal,cd_quadra_fiscal,cd_lote,cd_condominio,cd_tipo_lote,contribuinte_iptu,endereco,area_pol_lote,AC-1,...,ZM,ZMIS,ZMISa,ZMa,ZOE,ZPDS,ZPDSr,ZPI-1,ZPI-2,ZPR
0,210.008.0053-F.00,210,008,0053,00,F,210.008.0053-7,"R LUIS SALADIN, 187.0 - CID D'ABRIL, São Paul...",270.751684,0.0,...,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0
1,210.011.0047-F.00,210,011,0047,00,F,210.011.0047-4,"R MANUEL BENICIO, 257.0 - , São Paulo - SP. C...",176.359862,0.0,...,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0
2,210.016.0099-F.00,210,016,0099,00,F,210.016.0099-1,"R PERA-MARMELO, 472.0 - CID D ABRIL, São Paul...",150.331192,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,210.011.0087-F.00,210,011,0087,00,F,210.011.0087-3,"R MICAELA ALEGRIA, 70.0 - CID D ABRIL, São Pa...",145.726729,0.0,...,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0
4,210.008.0110-F.00,210,008,0110,00,F,210.008.0110-1,"R SIMAO MAYER, 117.0 - CID D ABRIL, São Paulo...",161.244863,0.0,...,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0

In [141]:
zoneamento.columns

Index(['id_lote', 'cd_setor_fiscal', 'cd_quadra_fiscal', 'cd_lote',
       'cd_condominio', 'cd_tipo_lote', 'contribuinte_iptu', 'endereco',
       'area_pol_lote', 'AC-1', 'AC-2', 'Praça/Canteiro', 'ZC', 'ZC-ZEIS',
       'ZCOR-1', 'ZCOR-2', 'ZCOR-3', 'ZCORa', 'ZCa', 'ZDE-1', 'ZDE-2',
       'ZEIS-1', 'ZEIS-2', 'ZEIS-3', 'ZEIS-4', 'ZEIS-5', 'ZEM', 'ZEMP', 'ZEP',
       'ZEPAM', 'ZER-1', 'ZER-2', 'ZERa', 'ZEU', 'ZEUP', 'ZEUPa', 'ZEUa', 'ZM',
       'ZMIS', 'ZMISa', 'ZMa', 'ZOE', 'ZPDS', 'ZPDSr', 'ZPI-1', 'ZPI-2',
       'ZPR'],
      dtype='str')

In [146]:
zoneamento['cd_tipo_lote'].unique()

<ArrowStringArray>
['F', 'M', 'V']
Length: 3, dtype: str

In [147]:
zoneamento = zoneamento[zoneamento['cd_tipo_lote']=='F'].reset_index(drop=True)

In [150]:
zoneamento['cd_lote'].str.len().unique()

array([4, 3, 2])

In [151]:
zoneamento['cd_lote'] = zoneamento['cd_lote'].str.zfill(4)

In [154]:
#checando aqui se os lotes já estão como 0000 para quando for ocndominio - e estão
assert (zoneamento[zoneamento['cd_condominio']!='00']['cd_lote']=='0000').all()

In [155]:
zoneamento['cd_setor_fiscal'].str.len().unique()

array([3])

In [156]:
zoneamento['cd_quadra_fiscal'].str.len().unique()

array([3, 2])

In [157]:
zoneamento['cd_quadra_fiscal'] = zoneamento['cd_quadra_fiscal'].str.zfill(3)

In [160]:
assert zoneamento['cd_setor_fiscal'].str.len().unique()==[3]
assert zoneamento['cd_setor_fiscal'].str.isdigit().all()

assert zoneamento['cd_quadra_fiscal'].str.len().unique()==[3]
assert zoneamento['cd_quadra_fiscal'].str.isdigit().all()

assert zoneamento['cd_lote'].str.len().unique()==[4]
assert zoneamento['cd_lote'].str.isdigit().all()

assert zoneamento['cd_condominio'].str.len().unique()==[2]
assert zoneamento['cd_condominio'].str.isdigit().all()

In [166]:
zoneamento['id_imovel'] = zoneamento['cd_setor_fiscal'] + '.' + zoneamento['cd_quadra_fiscal'] + '.' + zoneamento['cd_lote'] + '-' + zoneamento['cd_condominio']

In [167]:
nao_presentes = set(dados_finais['id_imovel'])- set(zoneamento['id_imovel'])

Tem poucos casos nao encontrados, mas também temos

In [169]:
len(nao_presentes)

1427

In [168]:
len(nao_presentes)/dados_finais['id_imovel'].nunique()

0.0008570421295965415

In [170]:
cols_zonas = ['AC-1', 'AC-2', 'Praça/Canteiro', 'ZC', 'ZC-ZEIS',
       'ZCOR-1', 'ZCOR-2', 'ZCOR-3', 'ZCORa', 'ZCa', 'ZDE-1', 'ZDE-2',
       'ZEIS-1', 'ZEIS-2', 'ZEIS-3', 'ZEIS-4', 'ZEIS-5', 'ZEM', 'ZEMP', 'ZEP',
       'ZEPAM', 'ZER-1', 'ZER-2', 'ZERa', 'ZEU', 'ZEUP', 'ZEUPa', 'ZEUa', 'ZM',
       'ZMIS', 'ZMISa', 'ZMa', 'ZOE', 'ZPDS', 'ZPDSr', 'ZPI-1', 'ZPI-2',
       'ZPR']

In [171]:
zoneamento[cols_zonas]

,AC-1,AC-2,Praça/Canteiro,ZC,ZC-ZEIS,ZCOR-1,ZCOR-2,ZCOR-3,ZCORa,ZCa,...,ZM,ZMIS,ZMISa,ZMa,ZOE,ZPDS,ZPDSr,ZPI-1,ZPI-2,ZPR
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,100.000,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,100.000,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,100.000,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,100.000,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3870626,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,100.000,0.0,0.0,0.0,0.0,0.0,0.0
3870627,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,100.000,0.0,0.0,0.0,0.0,0.0,0.0
3870628,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,49.991,0.0,0.0,0.0,0.0,0.0,0.0
3870629,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,100.000,0.0,0.0,0.0,0.0,0.0,0.0
3870630,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,100.000,0.0,0.0,0.0,0.0,0.0,0.0

In [178]:
nome_zona_prevalente = zoneamento[cols_zonas].idxmax(axis=1)

In [179]:
prop_zona_prevalente = zoneamento[cols_zonas].max(axis=1)

In [182]:
zoneamento_final = pd.concat([zoneamento['id_imovel'], nome_zona_prevalente, prop_zona_prevalente], axis=1).rename({0: 'zona_prevalente', 1: 'proporcao_zona_prevalente'}, axis=1)

In [183]:
zoneamento_final.duplicated().any()

np.True_

In [185]:
zoneamento_final = zoneamento_final.drop_duplicates()

In [186]:
zoneamento_final.shape

(1663941, 3)

In [189]:
dados_finais.shape

(1665031, 20)

In [190]:
dados_finais = pd.merge(dados_finais, zoneamento_final, on='id_imovel', how='left')

In [191]:
dados_finais.head()

,fid,cod_setor,tipo_qp,cod_qp,tipo_lote,cod_cond,cod_lote,cod_status,geometry,id_imovel,...,tp_uso_prevalente_unidade,tp_uso_prevalente_proporcao_por_unidade,tp_uso_prevalente_area,tp_uso_prevalente_proporcao_por_area,tp_padrao_construcao_prevalente_unidade,tp_padrao_construcao_prevalente_proporcao_por_unidade,tp_padrao_construcao_prevalente_por_area,tp_padrao_construcao_prevalente_proporcao_por_area,zona_prevalente,proporcao_zona_prevalente
0,8897614,026,F,029,F,01,0000,1,"POLYGON ((336597.97 7396029.548, 336598.446 73...",026.029.0000-01,...,20.0,0.79,20.0,0.75,22.0,0.79,22.0,0.75,ZEIS-3,100.0
1,8897615,026,F,029,F,02,0000,1,"POLYGON ((336599.851 7396011.968, 336599.515 7...",026.029.0000-02,...,41.0,0.50,41.0,0.50,42.0,0.50,42.0,0.50,ZEIS-3,100.0
2,8897616,026,F,029,F,00,0004,1,"POLYGON ((336607.867 7396035.303, 336608.524 7...",026.029.0004-00,...,42.0,1.00,42.0,1.00,31.0,1.00,31.0,1.00,ZEIS-3,100.0
3,8897617,026,F,029,F,00,0005,1,"POLYGON ((336615.334 7396026.727, 336613.723 7...",026.029.0005-00,...,42.0,1.00,42.0,1.00,32.0,1.00,32.0,1.00,ZEIS-3,100.0
4,8897618,026,F,029,F,00,0030,1,"POLYGON ((336621.614 7395998.454, 336617.064 7...",026.029.0030-00,...,42.0,1.00,42.0,1.00,31.0,1.00,31.0,1.00,ZEIS-3,100.0

In [192]:
save_parquet(dados_finais, 'dados_finais.parquet', subfolder='solicitacao_bruno_carano', gdf=True, output=True)

PosixPath('/home/hpougy/projects/zoneamento_lotes_pmsp/output/solicitacao_bruno_carano/dados_finais.parquet')

In [ ]:
#nao pode ter fid nas colunas no geopackage
dados_finais.rename(columns={'fid' : 'id_poligono_geosampa'}, inplace=True)

In [196]:
dados_finais.to_file('data/dados_bruno/dados_finais.gpkg', driver='GPKG')